import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Footer from '../components/Footer'
import Layout from '../components/Layout'
import Navbar from '../components/Navbar'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
    <Head>
      <title>Ninja List | Home</title>
    </Head>
    <div className={styles.container}>
    <Head>
      <title>Ninja List</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <h1 className={styles.title}>Homepage</h1>
    <p className={styles.text}>Client-side navigations to dynamic routes are handled with next/link. If we wanted to have links to the routes used above it will look like thi</p>
    <Link href="/ninjas"><a className={styles.btn}>See Ninja List</a></Link>
  
  </div>
    </>
  )
}
